enum APP_ASSETS {
  LOGO = "/assets/logos/logo_cistec.png",
  LOGO2 = "/assets/logos/logo_cistec_2.png",
  // LOGO_WHITE = "assets/logo_w.svg",
  MENU = "/assets/logo_menu.png",

  LOGO_INSTAGRAM = "/assets/social_media/logo_instagram.png",
  LOGO_FACEBOOK = "/assets/social_media/logo_facebook.png",
  LOGO_LINKEDIN = "/assets/social_media/logo_linkedin.png",
  // LOGO_INSTAGRAM_B = "/assets/logo_instagram_b.svg",
  // LOGO_FACEBOOK_B = "/assets/logo_facebook_b.svg",
  // LOGO_TIKTOK_B = "/assets/logo_tiktok_b.svg",
  // LOGO_LINKEDIN_B = "/assets/logo_linkedin_b.svg",
  // LOGO_WHATSAPP = "/assets/logo_whatsapp.svg",
  // LOGO_MOUSE = "/assets/logo_mouse.svg",
  // LOGO_MOUSE2 = "/assets/logo_mouse2.svg",
  // LOGO_NEXT = "/assets/logo_next.svg",
  // LOGO_BACK = "/assets/logo_back.svg",

  HOME_BG1 = "/assets/home/home_bg1.png",
  HOME_BG3 = "assets/home/home_bg3.png",
  HOME_BG4_1 = "assets/home/home_bg4_1.png",
  HOME_BG4_2 = "assets/home/home_bg4_2.png",
  HOME_BG4_3 = "assets/home/home_bg4_3.png",
  HOME_BG4_4 = "assets/home/home_bg4_4.png",
  HOME_BG4_5 = "assets/home/home_bg4_5.png",
  HOME_BG4_6 = "assets/home/home_bg4_6.png",
  HOME_BG4_7 = "assets/home/home_bg4_7.png",
  HOME_BG4_8 = "assets/home/home_bg4_8.png",
  HOME_BG4_9 = "assets/home/home_bg4_9.png",
  HOME_BG4_10 = "assets/home/home_bg4_10.png",
  HOME_BG4_11 = "assets/home/home_bg4_11.png",
  HOME_BG4_12 = "assets/home/home_bg4_12.png",
  HOME_BG5 = "assets/home/home_bg5.png",
  HOME_VIDEO6 = "assets/home/cistec_video_Institucional.mp4",
  HOME_BG8 = "assets/home/home_bg8.png",
  HOME_BG7 = "assets/home/home_bg7.png",

  HOME_IMG1 = "/assets/home/home_img1.png",
  HOME_IMG2 = "/assets/home/home_img2.png",
  HOME_IMG3 = "/assets/home/home_img3.png",

  ABOUT_BG1 = "/assets/about/about_bg1.png",

  CATALOG_BG1 = "/assets/catalog/catalog_bg1.png",
  CATALOG_BG3_1 = "/assets/catalog/catalog_bg3_1.png",
  CATALOG_BG3_2 = "/assets/catalog/catalog_bg3_2.png",
  CATALOG_BG3_3 = "/assets/catalog/catalog_bg3_3.png",
  CATALOG_IMG1 = "/assets/catalog/catalog_img1.png",
  CATALOG_IMG3_1 = "/assets/catalog/catalog_img3_1.png",
  CATALOG_IMG3_2 = "/assets/catalog/catalog_img3_2.png",
  CATALOG_IMG3_3 = "/assets/catalog/catalog_img3_3.png",
  CATALOG_IMG3_4 = "/assets/catalog/catalog_img3_4.png",
  CATALOG_IMG3_5 = "/assets/catalog/catalog_img3_5.png",
  CATALOG_IMG3_6 = "/assets/catalog/catalog_img3_6.png",


  // HOME_WHY1 = "/assets/home/why1.svg",
  // HOME_WHY2 = "/assets/home/why2.svg",
  // HOME_WHY3 = "/assets/home/why3.svg",
  // HOME_WHY4 = "/assets/home/why4.svg",
  // HOME_ABOUT1 = "/assets/home/about1.png",
  // HOME_ABOUT2 = "/assets/home/about2.png",

  OBRAS_BG1 = "/assets/obras/Obras1.png",
  OBRAS_BG2 = "/assets/obras/Obras2.png",
  OBRAS_BG2_1 = "/assets/obras/Obras2_1.png",
  OBRAS_BG2_2 = "/assets/obras/Obras2_2.png",
  OBRAS_BG2_3 = "/assets/obras/Obras2_3.png",
  OBRAS_BG2_4 = "/assets/obras/Obras2_4.png",
  OBRAS_BG2_5 = "/assets/obras/Obras2_5.png",
  OBRAS_BG2_6 = "/assets/obras/Obras2_6.png",
  OBRAS_BG2_7 = "/assets/obras/Obras2_7.png",
  OBRAS_BG2_8 = "/assets/obras/Obras2_8.png",
  OBRAS_BG2_9 = "/assets/obras/Obras2_9.png",
  OBRAS_BG2_10 = "/assets/obras/Obras2_10.png",
  OBRAS_BG2_11 = "/assets/obras/Obras2_11.png",
  OBRAS_BG2_12 = "/assets/obras/Obras2_12.png",

  CONTACT_BG1 = "/assets/contact/contact_bg1.png",
  CONTACT_BG2 = "/assets/contact/contact_bg2.png",
  CONTACT_ICON1 = "/assets/contact/contact_icon1.png",
  CONTACT_ICON2 = "/assets/contact/contact_icon2.png",
  CONTACT_ICON3 = "/assets/contact/contact_icon3.png",
  CONTACT_ICON4 = "/assets/contact/contact_icon4.png",
  CONTACT_ICON5 = "/assets/contact/contact_icon5.png",

  // PROYECTOS_BG = "/assets/proyectos/bg.png",
  // PROYECTO1_1 = "/assets/proyectos/pr1_1.png",
  // PROYECTO1_2 = "/assets/proyectos/pr1_2.png",
  // PROYECTO1_3 = "/assets/proyectos/pr1_3.png",
  // PROYECTO1_4 = "/assets/proyectos/pr1_4.png",
  // PROYECTO1_5 = "/assets/proyectos/pr1_5.png",
  // PROYECTO2_1 = "/assets/proyectos/pr2_1.png",
  // PROYECTO2_2 = "/assets/proyectos/pr2_2.png",
  // PROYECTO2_3 = "/assets/proyectos/pr2_3.png",
  // PROYECTO2_4 = "/assets/proyectos/pr2_4.png",
  // PROYECTO2_5 = "/assets/proyectos/pr2_5.png",
  // PROYECTO3_1 = "/assets/proyectos/pr3_1.png",
  // PROYECTO3_2 = "/assets/proyectos/pr3_2.png",
  // PROYECTO3_3 = "/assets/proyectos/pr3_3.png",
  // PROYECTO3_4 = "/assets/proyectos/pr3_4.png",
  // PROYECTO3_5 = "/assets/proyectos/pr3_5.png",

  // FOOTER_CONTACT = "/assets/footer/call-male.png",
  // FOOTER_MAIL = "/assets/footer/mail.png",
}

export default APP_ASSETS;
