enum APP_ASSETS {
  LOGO = "/assets/logos/logo_cistec.png",
  LOGO2 = "/assets/logos/logo_cistec_2.png",
  // LOGO_WHITE = "assets/logo_w.svg",
  MENU = "/assets/logo_menu.png",

  LOGO_INSTAGRAM = "/assets/social_media/logo_instagram.png",
  LOGO_FACEBOOK = "/assets/social_media/logo_facebook.png",
  LOGO_LINKEDIN = "/assets/social_media/logo_linkedin.png",
  // LOGO_INSTAGRAM_B = "/assets/logo_instagram_b.svg",
  // LOGO_FACEBOOK_B = "/assets/logo_facebook_b.svg",
  // LOGO_TIKTOK_B = "/assets/logo_tiktok_b.svg",
  // LOGO_LINKEDIN_B = "/assets/logo_linkedin_b.svg",
  // LOGO_WHATSAPP = "/assets/logo_whatsapp.svg",
  // LOGO_MOUSE = "/assets/logo_mouse.svg",
  // LOGO_MOUSE2 = "/assets/logo_mouse2.svg",
  // LOGO_NEXT = "/assets/logo_next.svg",
  // LOGO_BACK = "/assets/logo_back.svg",

  HOME_BG1 = "/assets/home/home_bg1.png",
  HOME_BG3 = "assets/home/home_bg3.png",
  HOME_BG4_1 = "assets/home/home_bg4_1.png",
  HOME_BG4_2 = "assets/home/home_bg4_2.png",
  HOME_BG4_3 = "assets/home/home_bg4_3.png",
  HOME_BG4_4 = "assets/home/home_bg4_4.png",
  HOME_BG4_5 = "assets/home/home_bg4_5.png",
  HOME_BG4_6 = "assets/home/home_bg4_6.png",
  HOME_BG4_7 = "assets/home/home_bg4_7.png",
  HOME_BG4_8 = "assets/home/home_bg4_8.png",
  HOME_BG4_9 = "assets/home/home_bg4_9.png",
  HOME_BG4_10 = "assets/home/home_bg4_10.png",
  HOME_BG4_11 = "assets/home/home_bg4_11.png",
  HOME_BG4_12 = "assets/home/home_bg4_12.png",
  HOME_BG5 = "assets/home/home_bg5.png",
  HOME_VIDEO6 = "assets/home/cistec_video_Institucional.mp4",
  HOME_BG8 = "assets/home/home_bg8.png",
  HOME_BG7 = "assets/home/home_bg7.png",

  HOME_IMG1 = "/assets/home/home_img1.png",
  HOME_IMG2 = "/assets/home/home_img2.png",
  HOME_IMG3 = "/assets/home/home_img3.png",

  ABOUT_BG1 = "/assets/about/about_bg1.png",

  CONTACT_BG1 = "/assets/contact/contact_bg1.png",
  CONTACT_BG2 = "/assets/contact/contact_bg2.png",
  CONTACT_ICON1 = "/assets/contact/contact_icon1.png",
  CONTACT_ICON2 = "/assets/contact/contact_icon2.png",
  CONTACT_ICON3 = "/assets/contact/contact_icon3.png",
  CONTACT_ICON4 = "/assets/contact/contact_icon4.png",
  CONTACT_ICON5 = "/assets/contact/contact_icon5.png",
  // HOME_WHY1 = "/assets/home/why1.svg",
  // HOME_WHY2 = "/assets/home/why2.svg",
  // HOME_WHY3 = "/assets/home/why3.svg",
  // HOME_WHY4 = "/assets/home/why4.svg",
  // HOME_ABOUT1 = "/assets/home/about1.png",
  // HOME_ABOUT2 = "/assets/home/about2.png",

  // HOME_BRAND1 = "/assets/home/brand1.png",
  // HOME_BRAND2 = "/assets/home/brand2.png",
  // HOME_BRAND3 = "/assets/home/brand3.png",
  // HOME_BRAND4 = "/assets/home/brand4.png",
  // HOME_BRAND5 = "/assets/home/brand5.png",
  // HOME_BRAND6 = "/assets/home/brand6.png",
  // HOME_BRAND7 = "/assets/home/brand7.png",
  // HOME_BRAND8 = "/assets/home/brand8.png",
  // HOME_BRAND9 = "/assets/home/brand9.png",
  // HOME_BRAND10 = "/assets/home/brand10.png",

  // HOME_SERVICIO1 = "/assets/home/servicio1.png",
  // HOME_SERVICIO2 = "/assets/home/servicio2.png",
  // HOME_SERVICIO2A = "/assets/home/servicio2a.png",
  // HOME_SERVICIO3 = "/assets/home/servicio3.png",
  // HOME_SERVICIO4 = "/assets/home/servicio4.png",
  // HOME_SERVICIO4A = "/assets/home/servicio4a.png",
  // HOME_SERVICIO5 = "/assets/home/servicio5.png",

  // HOME_PROYECTOS1 = "/assets/home/proyectos1.png",
  // HOME_PROYECTOS2 = "/assets/home/proyectos2.png",
  // HOME_PROYECTOS3 = "/assets/home/proyectos3.png",
  // HOME_PROYECTOS4 = "/assets/home/proyectos4.png",
  // HOME_PROYECTOS5 = "/assets/home/proyectos5.png",
  // HOME_PROYECTOS6 = "/assets/home/proyectos6.png",
  // HOME_PROYECTOS7 = "/assets/home/proyectos7.png",
  // HOME_PROYECTOS8 = "/assets/home/proyectos8.png",
  // HOME_PROYECTOS9 = "/assets/home/proyectos9.png",
  // HOME_PROYECTOS10 = "/assets/home/proyectos10.png",
  // HOME_PROYECTOS11 = "/assets/home/proyectos11.png",
  // HOME_PROYECTOS12 = "/assets/home/proyectos12.png",

  // NOSOTROS_BG1 = "/assets/nosotros/bg1.png",
  // NOSOTROS_BG2 = "/assets/nosotros/bg2.png",
  // NOSOTROS_BG3 = "/assets/nosotros/bg3.png",
  // NOSOTROS_BG4 = "/assets/nosotros/bg4.png",
  // NOSOTROS_BG5 = "/assets/nosotros/bg5.png",
  // NOSOTROS_LOGO1 = "/assets/nosotros/logo1.svg",
  // NOSOTROS_LOGO2 = "/assets/nosotros/logo2.svg",
  // NOSOTROS_LOGO3 = "/assets/nosotros/logo3.svg",
  // NOSOTROS_LOGO4 = "/assets/nosotros/logo4.svg",
  // NOSOTROS_COMILLAS = "/assets/nosotros/comilla.svg",

  // SERVICIOS_IMG1 = "/assets/servicios/img1.png",
  // SERVICIOS_IMG2 = "/assets/servicios/img2.png",
  // SERVICIOS_IMG3 = "/assets/servicios/img3.png",
  // SERVICIOS_IMG4 = "/assets/servicios/img4.png",
  // SERVICIOS_IMG5 = "/assets/servicios/img5.png",
  // SERVICIOS_IMG6 = "/assets/servicios/img4.png",
  // SERVICIOS_IMG7 = "/assets/servicios/img7.png",
  // SERVICIOS_IMG8 = "/assets/servicios/img8.png",
  // SERVICIOS_IMG9 = "/assets/servicios/img9.png",
  // SERVICIOS_IMG10 = "/assets/servicios/img10.png",
  // SERVICIOS_IMG11 = "/assets/servicios/img11.png",
  // SERVICIOS_IMG12 = "/assets/servicios/img12.png",
  // SERVICIOS_IMG13 = "/assets/servicios/img13.png",
  // SERVICIOS_TRANSICION = "/assets/servicios/transicion.png",
  // SERVICIOS_BARRA_1 = "/assets/servicios/barra_1.png",
  // SERVICIOS_BARRA_2 = "/assets/servicios/barra_2.png",
  // SERVICIOS_BARRA_3 = "/assets/servicios/barra_3.png",
  // SERVICIOS_ELIPSE_2 = "/assets/servicios/ellipse_2.png",
  // SERVICIOS_NUMBER_1 = "/assets/servicios/number_1.png",
  // SERVICIOS_NUMBER_2 = "/assets/servicios/number_2.png",
  // SERVICIOS_NUMBER_3 = "/assets/servicios/number_3.png",
  // SERVICIOS_NUMBER_4 = "/assets/servicios/number_4.png",
  // SERVICIOS_NUMBER_5 = "/assets/servicios/number_5.png",
  // SERVICIOS_NUMBER_6 = "/assets/servicios/number_6.png",
  // SERVICIOS_NUMBER_7 = "/assets/servicios/number_7.png",
  // SERVICIOS_NUMBER_8 = "/assets/servicios/number_8.png",
  // SERVICIOS_NUMBER_9 = "/assets/servicios/number_9.png",
  // SERVICIOS_NUMBER_10 = "/assets/servicios/number_10.png",
  // SERVICIOS_NUMBER_11 = "/assets/servicios/number_11.png",
  // SERVICIOS_NUMBER_12 = "/assets/servicios/number_12.png",
  // SERVICIOS_NUMBER_13 = "/assets/servicios/number_13.png",

  // PROYECTOS_BG = "/assets/proyectos/bg.png",
  // PROYECTO1_1 = "/assets/proyectos/pr1_1.png",
  // PROYECTO1_2 = "/assets/proyectos/pr1_2.png",
  // PROYECTO1_3 = "/assets/proyectos/pr1_3.png",
  // PROYECTO1_4 = "/assets/proyectos/pr1_4.png",
  // PROYECTO1_5 = "/assets/proyectos/pr1_5.png",
  // PROYECTO2_1 = "/assets/proyectos/pr2_1.png",
  // PROYECTO2_2 = "/assets/proyectos/pr2_2.png",
  // PROYECTO2_3 = "/assets/proyectos/pr2_3.png",
  // PROYECTO2_4 = "/assets/proyectos/pr2_4.png",
  // PROYECTO2_5 = "/assets/proyectos/pr2_5.png",
  // PROYECTO3_1 = "/assets/proyectos/pr3_1.png",
  // PROYECTO3_2 = "/assets/proyectos/pr3_2.png",
  // PROYECTO3_3 = "/assets/proyectos/pr3_3.png",
  // PROYECTO3_4 = "/assets/proyectos/pr3_4.png",
  // PROYECTO3_5 = "/assets/proyectos/pr3_5.png",

  // FOOTER_CONTACT = "/assets/footer/call-male.png",
  // FOOTER_MAIL = "/assets/footer/mail.png",
}

export default APP_ASSETS;
